export const motivationalQuotes = [
  "Believe you can and you're halfway there.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The only way to do great work is to love what you do.",
  "Dream big and dare to fail.",
  "Start where you are. Use what you have. Do what you can.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "It always seems impossible until it's done.",
  "You are never too old to set another goal or to dream a new dream.",
  "Act as if what you do makes a difference. It does.",
  "Quality is not an act, it is a habit.",
  "With the new day comes new strength and new thoughts.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Opportunities don't happen, you create them.",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "You don’t have to be great to start, but you have to start to be great.",
  "If you can dream it, you can do it.",
  "Great things never come from comfort zones.",
  "Push yourself, because no one else is going to do it for you.",
  "Success doesn’t just find you. You have to go out and get it.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Dream it. Wish it. Do it.",
  "Don’t stop when you’re tired. Stop when you’re done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Do something today that your future self will thank you for.",
  "Little things make big days.",
  "It’s going to be hard, but hard does not mean impossible."
];